

<?php


$fname = $_POST["fname"];
$lname = $_POST["lname"];
$email = strval($_POST["email"]);
$phoneno = $_POST["phoneno"];
$gender = $_POST["gender"];
$dob = $_POST["dob"];
$conn = new mysqli("localhost", "root", "", "test");
if (!$conn) {
    echo "Connection Failed";
    die;
} else {
    $check1 = "SELECT * FROM sign_up WHERE email = '$_POST[email]' or phoneno = '$_POST[phoneno]'";
    $rs1 = mysqli_query($conn, $check1);
    $rows = mysqli_fetch_array($rs1, MYSQLI_BOTH);
    $count = mysqli_num_rows($rs1);

    if ($rows != null and $rows['email'] == $email and $rows['phoneno'] == $phoneno) {
        echo "<link rel='stylesheet' href='sign_in.css'>"; 
        echo "<div class='main'>";
        echo "<center>";
        echo "<h1>abc Travels</h1>";
        echo "<h2>Sign Up</h2>";
        echo "    <form id='myform' name='myform' action='Sign_Up_page.php' method='post'>";
        echo "        <input type='text' placeholder='First Name' id='fname' class='inp' name='fname'>";
        echo '        <input type="text" placeholder="Last Name" id="lname" class="inp" name="lname"><br>';
        echo '        <input type="text" placeholder="Email ID" id="email" class="inp" name="email">';
        echo '        <input type="number" placeholder="Phone Number" id="num" class="inp" min="1000000000" max="9999999999"';
        echo '            name="phoneno"><br>';
        echo '        <b style="font-size: 120%;">Gender:</b>';
        echo '        <input type="radio" id="M" name="gender" value="Male">';
        echo '        <label for="M">Male</label>';
        echo '        <input type="radio" id="F" name="gender" value="Female">';
        echo '        <label for="M">Female</label><br>';
        echo "        <input type='date' placeholder='DOB' id='dob' class='inp' name='dob'><br>";
        echo '        <input type="button" id="submit" class="submit" value="Validate">';
        echo '        <div id="submitdiv"></div>';
        echo "";
        echo '<div class="result">';
        echo "E-Mail ID and Phone Number Exists";
        echo '</div>';
        echo "<center>";
        echo "    <div class='user'>";
        echo "        <p> <a href='sign_in_page_nocom.html'>Sign In</a></p>";
        echo "    </div>";
        echo "</center>";
        echo '    </form>';
        echo '</center>';
        echo "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js'></script>";
        echo "<script src='Sign_Up.js'></script>";
        echo '</div>';
    } elseif ($rows != null and $rows['email'] == $email and $rows['phoneno'] != $phoneno) {
        echo "<link rel='stylesheet' href='sign_in.css'>";
        echo "<div class='main'>";
        echo "<center>";
        echo "<h1>abc Travels</h1>";
        echo "<h2>Sign Up</h2>";
        echo "    <form id='myform' name='myform' action='Sign_Up_page.php' method='post'>";
        echo "        <input type='text' placeholder='First Name' id='fname' class='inp' name='fname'>";
        echo '        <input type="text" placeholder="Last Name" id="lname" class="inp" name="lname"><br>';
        echo '        <input type="text" placeholder="Email ID" id="email" class="inp" name="email">';
        echo '        <input type="number" placeholder="Phone Number" id="num" class="inp" min="1000000000" max="9999999999"';
        echo '            name="phoneno"><br>';
        echo '        <b style="font-size: 120%;">Gender:</b>';
        echo '        <input type="radio" id="M" name="gender" value="Male">';
        echo '        <label for="M">Male</label>';
        echo '        <input type="radio" id="F" name="gender" value="Female">';
        echo '        <label for="M">Female</label><br>';
        echo "        <input type='date' placeholder='DOB' id='dob' class='inp' name='dob'><br>";
        echo '        <input type="button" id="submit" class="submit" value="Validate">';
        echo '        <div id="submitdiv"></div>';
        echo "";
        echo '<div class="result">';
        echo "E-Mail ID Exists";
        echo '</div>';
        echo "<center>";
        echo "    <div class='user'>";
        echo "        <p> <a href='sign_in_page_nocom.html'>Sign In</a></p>";
        echo "    </div>";
        echo "</center>";
        echo '    </form>';
        echo '</center>';
        echo "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js'></script>";
        echo "<script src='Sign_Up.js'></script>";
        echo '</div>';
    } elseif ($rows != null and $rows['email'] != $email and $rows['phoneno'] == $phoneno) {
        echo "<link rel='stylesheet' href='sign_in.css'>";
        echo "<div class='main'>";
        echo "<center>";
        echo "<h1>abc Travels</h1>";
        echo "<h2>Sign Up</h2>";
        echo "    <form id='myform' name='myform' action='Sign_Up_page.php' method='post'>";
        echo "        <input type='text' placeholder='First Name' id='fname' class='inp' name='fname'>";
        echo '        <input type="text" placeholder="Last Name" id="lname" class="inp" name="lname"><br>';
        echo '        <input type="text" placeholder="Email ID" id="email" class="inp" name="email">';
        echo '        <input type="number" placeholder="Phone Number" id="num" class="inp" min="1000000000" max="9999999999"';
        echo '            name="phoneno"><br>';
        echo '        <b style="font-size: 120%;">Gender:</b>';
        echo '        <input type="radio" id="M" name="gender" value="Male">';
        echo '        <label for="M">Male</label>';
        echo '        <input type="radio" id="F" name="gender" value="Female">';
        echo '        <label for="M">Female</label><br>';
        echo "        <input type='date' placeholder='DOB' id='dob' class='inp' name='dob'><br>";
        echo '        <input type="button" id="submit" class="submit" value="Validate">';
        echo '        <div id="submitdiv"></div>';
        echo "";
        echo '<div class="result">';
        echo "Phone Number Exists";
        echo '</div>';
        echo "<center>";
        echo "    <div class='user'>";
        echo "        <p> <a href='sign_in_page_nocom.html'>Sign In</a></p>";
        echo "    </div>";
        echo "</center>";
        echo '    </form>';
        echo '</center>';
        echo "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js'></script>";
        echo "<script src='Sign_Up.js'></script>";
        echo '</div>';
    } else {
        $query = $conn->prepare("insert into sign_up(fname,lname,email,phoneno,gender,dob) values('$fname','$lname','$email','$phoneno','$gender','$dob')");
        $query->execute();
        echo "<link rel='stylesheet' href='sign_in.css'>";
        echo "<div class='main'>";
        echo "<center>";
        echo "<h1>abc Travels</h1>";
        echo "<h2>Sign Up</h2>";
        echo "    <form id='myform' name='myform' action='Sign_Up_page.php' method='post'>";
        echo "        <input type='text' placeholder='First Name' id='fname' class='inp' name='fname'>";
        echo '        <input type="text" placeholder="Last Name" id="lname" class="inp" name="lname"><br>';
        echo '        <input type="text" placeholder="Email ID" id="email" class="inp" name="email">';
        echo '        <input type="number" placeholder="Phone Number" id="num" class="inp" min="1000000000" max="9999999999"';
        echo '            name="phoneno"><br>';
        echo '        <b style="font-size: 120%;">Gender:</b>';
        echo '        <input type="radio" id="M" name="gender" value="Male">';
        echo '        <label for="M">Male</label>';
        echo '        <input type="radio" id="F" name="gender" value="Female">';
        echo '        <label for="M">Female</label><br>';
        echo "        <input type='date' placeholder='DOB' id='dob' class='inp' name='dob'><br>";
        echo '        <input type="button" id="submit" class="submit" value="Validate">';
        echo '        <div id="submitdiv"></div>';
        echo "";
        echo '<div class="result">';
        echo "Sign Up Successful";
        echo '</div>';
        echo '    </form>';
        echo '</center>';
        echo "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js'></script>";
        echo "<script src='Sign_Up.js'></script>";
        echo "<center>";
        echo "<a href='sign_in_page_nocom.html'><input type='button' id='submit' class='submit' value='Log In'></a>";
        echo "</center>";
        echo '</div>';
        $query->close();
    }
    $conn->close();
}
